version: '3.8'

volumes:
    __volume_name__: {}

services:
    __container_name__:
        build:
            context: __context__
            dockerfile: __dockerfile_path__
            target: __container_name__
            cache_from:
                - __container_name__:latest
        image: __container_name__
        container_name: __container_name__
        ports:
            - __local_port__:__container_port__
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '5'