version: '3.8'

volumes:
    __volume_name__: {}

services:
    __container_name__:
        build:
            context: __context__
            dockerfile: __dockerfile_path__
            target: __container_name__
            cache_from:
                - __container_name__:latest
        image: __container_name__
        container_name: __container_name__
        restart: always
        ports:
            - __local_port__:__container_port__
        healthcheck:
            test: bash -c "</dev/tcp/__container_name__/__container_port && exit 0 || exit 1"
            start_period: 30s
            interval: 30s
            timeout: 10s
            retries: 3
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '5'